import * as Fs from "node:fs"

import * as anchor from "@coral-xyz/anchor"
import { Keypair } from "@solana/web3.js"

import type { SplMintRecord } from "./realFlowTypes.js"

/** Read and narrow the Anchor IDL generated by the Solana outpost build. */
export function readAnchorIdl(path: string): anchor.Idl {
  const parsed: unknown = JSON.parse(Fs.readFileSync(path, "utf-8"))
  return narrowAnchorIdl(parsed, path)
}

/** Read persisted mock SPL mint metadata from the cluster bootstrap. */
export function readSplMints(path: string): readonly SplMintRecord[] {
  const parsed: unknown = JSON.parse(Fs.readFileSync(path, "utf-8"))
  if (!Array.isArray(parsed))
    throw new Error(`SPL mint file is not an array: ${path}`)
  return parsed.map(readSplMintRecord)
}

/** Read a persisted Solana keypair secret-key array. */
export function readKeypair(path: string): Keypair {
  const parsed: unknown = JSON.parse(Fs.readFileSync(path, "utf-8"))
  if (
    !Array.isArray(parsed) ||
    parsed.some(value => typeof value !== "number")
  ) {
    throw new Error(`Solana keypair file is not a number array: ${path}`)
  }
  return Keypair.fromSecretKey(Uint8Array.from(parsed))
}

function narrowAnchorIdl(value: unknown, path: string): anchor.Idl {
  if (
    typeof value !== "object" ||
    value === null ||
    !("instructions" in value)
  ) {
    throw new Error(`Anchor IDL is missing instructions: ${path}`)
  }
  return value as anchor.Idl
}

function readSplMintRecord(value: unknown): SplMintRecord {
  if (
    typeof value !== "object" ||
    value === null ||
    !("code" in value) ||
    !("mint" in value) ||
    !("decimals" in value)
  ) {
    throw new Error("SPL mint record is missing code, mint, or decimals")
  }
  return {
    code: Number(value.code),
    mint: String(value.mint),
    decimals: Number(value.decimals)
  }
}
