import { NodeopProcess } from "../../cluster/processes/NodeopProcess.js"
import type { Renderer } from "../../utils/Renderer.js"
import {
  shellQuote,
  StartScriptVariable
} from "../../utils/startScriptUtils.js"
import type { ApiNodeConfig } from "../ApiNodeConfig.js"
import { ClusterConfigProvider } from "../ClusterConfigProvider.js"
import type { DaemonConfig } from "../DaemonConfig.js"
import { StartScriptRenderer } from "./StartScriptRenderer.js"

/**
 * Renders a STANDALONE API node's `start.sh` — the `create-api-node` companion
 * to its `config.ini`.
 *
 * Shares exactly the pieces that are genuinely cluster-independent with
 * {@link StartScriptRenderer}: the shebang, `set -euo pipefail`, the
 * `WIRE_PREFIX_PATH` → `command -v nodeop` → `WIRE_BUILD_PATH` resolution chain
 * ({@link StartScriptRenderer.prefixResolution}) so an installed host needs no
 * configuration at all, and the `CONDITIONAL_ARGS` block
 * ({@link StartScriptRenderer.conditionLines}) that carries the
 * `--trace-no-abis` capability probe.
 *
 * **The probe is not optional.** This node loads `trace_api_plugin`, and newer
 * nodeop generations hard-fail that plugin's init WITHOUT
 * {@link NodeopProcess.TraceNoAbisFlag} while older ones reject the unknown
 * option WITH it. The answer belongs to the host that RUNS the script, not to
 * whichever machine generated it — `create-api-node` never even sees a nodeop
 * binary — so the flag is emitted as a run-time `--help` test appended to
 * `CONDITIONAL_ARGS`, exactly as a cluster node's `start.sh` does.
 *
 * Everything else is deliberately NOT shared, because the cluster forms assume a
 * cluster: `StartScriptRenderer.preamble` hard-codes the `cluster-config.json`
 * probe and the `../..` `CLUSTER_DIR` derivation, `HeaderComment` names
 * `wire-cluster-tool run`, and `execTarget` / `removeRun` take a `DaemonConfig`
 * plus a relocation table. A standalone node has no cluster root and no
 * relocations, so this script carries none of them.
 */
export class ApiNodeStartScriptRenderer implements Renderer {
  constructor(private readonly config: ApiNodeConfig) {}

  render(): string {
    const lines = [
      StartScriptRenderer.Shebang,
      StartScriptRenderer.StrictMode,
      "",
      ...ApiNodeStartScriptRenderer.HeaderComment,
      "",
      ApiNodeStartScriptRenderer.NodeDirLine,
      ...StartScriptRenderer.prefixResolution(),
      "",
      ...StartScriptRenderer.conditionLines(
        ApiNodeStartScriptRenderer.conditions(),
        ApiNodeStartScriptRenderer.Relocations
      ),
      `exec ${ApiNodeStartScriptRenderer.execTarget()} \\`,
      ...ApiNodeStartScriptRenderer.argvLines(this.config).map(
        line => `  ${line} \\`
      ),
      `  ${StartScriptRenderer.ConditionalArrayExpansion}`,
      ""
    ]
    return lines.join("\n")
  }
}

export namespace ApiNodeStartScriptRenderer {
  /** Fixed header — no secret notice: a standalone API node signs nothing. */
  export const HeaderComment = [
    "# Generated by wire-cluster-tool create-api-node — starts this standalone",
    "# WIRE API node against the config.ini beside this script.",
    "#",
    "# Invoke as:  ./start.sh"
  ]

  /**
   * `$NODE_DIR` — this script's own directory, which is BOTH the config dir and
   * the parent of the data dir. Derived from `BASH_SOURCE` so the emitted
   * directory relocates freely; there is no `$CLUSTER_DIR` counterpart because a
   * standalone node has no cluster root above it.
   */
  export const NodeDirLine = `${StartScriptVariable.NODE_DIR}="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"`

  /**
   * The relocation table for a standalone node: EMPTY.
   *
   * Nothing in this script carries a build-host absolute path — the exec target
   * is expressed against `$WIRE_PREFIX_PATH` and every argv value against
   * `$NODE_DIR` — so there is no prefix to rewrite, and the conditional tokens
   * simply render single-quoted.
   */
  export const Relocations = [] as const

  /**
   * The run-time conditionals this script evaluates: the `--trace-no-abis`
   * capability probe against the RESOLVED nodeop, and nothing else.
   *
   * @returns The conditions, in the shape {@link StartScriptRenderer.conditionLines} renders.
   */
  export function conditions(): DaemonConfig["conditions"] {
    return [
      {
        test: NodeopProcess.traceNoAbisProbeTest(execTarget()),
        tokens: [NodeopProcess.TraceNoAbisFlag]
      }
    ]
  }

  /**
   * The `exec` target — nodeop under the RESOLVED prefix, in the same
   * expanded-variable + single-quoted-remainder shape `toRelocatableToken`
   * produces, so the variable expands while the path tail stays inert.
   * {@link StartScriptRenderer.PrefixProbeBinary} is THE spelling of the binary
   * name and {@link ClusterConfigProvider.BinSubpath} THE spelling of its
   * directory — both reused rather than re-declared.
   *
   * @returns The shell word to `exec`.
   */
  export function execTarget(): string {
    return `"$${StartScriptVariable.WIRE_PREFIX_PATH}"${shellQuote(
      `/${ClusterConfigProvider.BinSubpath}/${StartScriptRenderer.PrefixProbeBinary}`
    )}`
  }

  /**
   * The `exec`'d argv, one `--flag <value>` per line — the flag spellings come
   * from {@link NodeopProcess}, which owns them for the cluster argv too.
   * `--genesis-json` is present only when the config carries a genesis file —
   * which the command has by then copied next to this script — so a node started
   * from a data dir or a snapshot is never handed a path that does not exist.
   *
   * @param config - The resolved API-node config.
   * @returns One shell line per flag pair.
   */
  export function argvLines(config: ApiNodeConfig): string[] {
    const nodeDir = `"$${StartScriptVariable.NODE_DIR}"`
    return [
      `${NodeopProcess.ConfigDirFlag} ${nodeDir}`,
      `${NodeopProcess.DataDirFlag} ${nodeDir}${shellQuote(
        `/${ClusterConfigProvider.DataSubpath}`
      )}`,
      ...(config.genesisJsonFile != null
        ? [
            `${NodeopProcess.GenesisJsonFlag} ${nodeDir}${shellQuote(
              `/${ClusterConfigProvider.GenesisFilename}`
            )}`
          ]
        : [])
    ]
  }
}
