import type { Renderer } from "../../utils/Renderer.js"
import {
  matchesPrefix,
  orderRelocations,
  toRelocatableArgv,
  toRelocatableToken,
  shellQuote,
  StartScriptVariable,
  type StartScriptRelocation
} from "../../utils/startScriptUtils.js"
import type { DaemonConfig } from "../DaemonConfig.js"
import { isNotEmpty } from "../../utils/predicateUtils.js"

/**
 * Renders a daemon's `start.sh` — the command the harness would spawn for it,
 * relocated so the script runs wherever the cluster tree is unpacked.
 *
 * Two properties are load-bearing:
 *
 * - **RUN semantics, not create semantics.** The argv comes from the daemon's
 *   run-phase form (nodeop relaunch-stripped, anvil with interval mining), so
 *   an operator restarting a daemon gets the same process the harness's own
 *   `run` would, including any extra environment its managed process supplies.
 * - **Build-time conditionals render as SHELL.** A flag whose presence depended
 *   on the build host (anvil's `--load-state`, nodeop's probed
 *   `--trace-no-abis`) is emitted as a test the script evaluates, never frozen.
 */
export class StartScriptRenderer implements Renderer {
  constructor(
    private readonly daemon: DaemonConfig,
    private readonly clusterRelocations: readonly StartScriptRelocation[]
  ) {}

  /** The daemon's relocations ahead of the cluster-wide ones (nodePath out-ranks clusterPath). */
  private get relocations(): StartScriptRelocation[] {
    return orderRelocations([
      ...this.daemon.relocations,
      ...this.clusterRelocations
    ])
  }

  render(): string {
    const { daemon } = this,
      relocations = this.relocations,
      argv = daemon.conditions.reduce(
        (remaining, condition) =>
          StartScriptRenderer.removeRun(remaining, condition.tokens),
        [...daemon.argv]
      ),
      lines = [
        StartScriptRenderer.Shebang,
        StartScriptRenderer.StrictMode,
        "",
        ...StartScriptRenderer.HeaderComment,
        "",
        ...StartScriptRenderer.preamble(daemon, relocations),
        "",
        ...StartScriptRenderer.environmentLines(daemon),
        ...StartScriptRenderer.conditionLines(daemon.conditions, relocations),
        `exec ${StartScriptRenderer.execTarget(daemon, relocations)} \\`,
        ...toRelocatableArgv(argv, relocations).map(word => `  ${word} \\`),
        `  ${StartScriptRenderer.ConditionalArrayExpansion}`,
        ""
      ]
    return lines.join("\n")
  }
}

export namespace StartScriptRenderer {
  export const Shebang = "#!/usr/bin/env bash"
  export const StrictMode = "set -euo pipefail"
  /** Bash array collecting every condition's tokens, expanded into the `exec`. */
  export const ConditionalArrayName = "CONDITIONAL_ARGS"

  /**
   * Shell exports for the extra environment a live managed process merges over
   * its inherited environment — rendered as DEFAULTS, not overrides.
   *
   * Each line is `[ -n "${NAME:-}" ] || export NAME=<value>`, so an operator's own
   * `NAME` survives a `start.sh` relaunch. That is what keeps the script
   * faithful to the managed spawn: the harness resolves these values against
   * the ambient environment at spawn time (e.g.
   * `SolanaValidatorProcess.resolveEnv` defers to an operator-set `RUST_LOG`),
   * and a frozen `export NAME=value` would silently win over the operator
   * instead — the "build-time conditionals render as SHELL" invariant in this
   * class's header, applied to environment rather than argv.
   *
   * @param daemon - The daemon being rendered.
   * @returns Safely quoted defaulting `export` lines, blank-line terminated
   *   when non-empty so the section reads as its own block.
   */
  export function environmentLines(daemon: DaemonConfig): string[] {
    const lines = Object.entries(daemon.env ?? {}).map(
      // A GUARDED assignment, not a `${NAME:-…}` expansion: the default keeps
      // {@link shellQuote}'s fully-inert single-quoted form, which cannot appear
      // inside an expansion word (bash re-parses quotes there, so a value
      // containing `'` would break the script).
      ([name, value]) =>
        `[ -n "\${${name}:-}" ] || export ${name}=${shellQuote(value)}`
    )
    return isNotEmpty(lines) ? [...lines, ""] : lines
  }

  /**
   * Fixed header. The secret notice is NOT decoration: under the default `KEY`
   * signature provider a producer/operator nodeop argv carries an inline
   * `--signature-provider <pubkey>=KEY:<private>`, and unlike `config.ini`
   * (which emits a provider ONLY for the bios node) this file therefore puts a
   * private key on disk for every non-bios node. Published GHA artifacts are
   * unaffected — that workflow is SSM-only, so those render `SSM:<id>`.
   */
  export const HeaderComment = [
    "# Generated by wire-cluster-tool — starts this daemon with the same argv",
    "# the harness uses for `wire-cluster-tool run`.",
    "#",
    "# NOTE: under a KEY-mode cluster this file contains an inline signing key.",
    "#",
    "# Invoke as:  ./start.sh"
  ]

  /**
   * The preamble that makes the relocation variables real.
   *
   * `CLUSTER_DIR` is overridable and ASSERTED. The `../..` derivation holds
   * inside a live cluster tree (`<cluster>/data/<daemon>/`) but NOT in a
   * `wire-cluster-tool package` per-node archive, whose layout is
   * `<extract>/<nodeName>/` — one level, where `../..` resolves to a
   * valid-but-wrong grandparent and `cd` silently succeeds. The
   * `cluster-config.json` probe converts that into a loud error naming the
   * override. (It cannot rescue the package case — that archive carries no
   * `cluster-config.json` — and it cannot catch `WIRE_CLUSTER_DIR` pointed at a
   * DIFFERENT valid cluster, which is inherent to an explicit override.)
   *
   * @param daemon - The daemon being rendered.
   * @returns Preamble lines.
   */
  export function preamble(
    daemon: DaemonConfig,
    relocations: readonly StartScriptRelocation[]
  ): string[] {
    return [
      `${StartScriptVariable.NODE_DIR}="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"`,
      `${StartScriptVariable.CLUSTER_DIR}="\${WIRE_CLUSTER_DIR:-$(cd "$${StartScriptVariable.NODE_DIR}/../.." && pwd)}"`,
      `[ -f "$${StartScriptVariable.CLUSTER_DIR}/cluster-config.json" ] || {`,
      `  echo "start.sh: cluster root not found at $${StartScriptVariable.CLUSTER_DIR} — set WIRE_CLUSTER_DIR" >&2`,
      "  exit 1",
      "}",
      ...(referencesRoot(
        daemon,
        relocations,
        StartScriptVariable.WIRE_PREFIX_PATH
      )
        ? prefixResolution()
        : []),
      ...requiredRootAssertions(daemon, relocations)
    ]
  }

  /**
   * Does this daemon's argv (or a conditional's tokens) actually sit under the
   * root `variable` stands for?
   *
   * @param daemon - The daemon being rendered.
   * @param relocations - Ordered relocation table.
   * @param variable - The root in question.
   * @returns `true` when at least one token relocates onto that root.
   */
  export function referencesRoot(
    daemon: DaemonConfig,
    relocations: readonly StartScriptRelocation[],
    variable: StartScriptVariable
  ): boolean {
    const tokens = [
      daemon.exe,
      ...daemon.argv,
      ...daemon.conditions.flatMap(condition => [...condition.tokens])
    ]
    return relocations
      .filter(relocation => relocation.variable === variable)
      .some(relocation =>
        tokens.some(token => matchesPrefix(token, relocation.prefix))
      )
  }

  /**
   * `: "${VAR:?…}"` guards for each host-supplied root this daemon's argv
   * actually references. Only the roots in play are asserted — a depot-only
   * daemon must not demand `$WIRE_SOLANA_PATH`.
   *
   * @param daemon - The daemon being rendered.
   * @param relocations - Ordered relocation table (cluster-wide + per-daemon).
   * @returns Assertion lines (possibly empty).
   */
  export function requiredRootAssertions(
    daemon: DaemonConfig,
    relocations: readonly StartScriptRelocation[]
  ): string[] {
    return HostSuppliedRoots.filter(variable =>
      referencesRoot(daemon, relocations, variable)
    ).map(
      variable =>
        `: "\${${variable}:?set to the ${RootDescriptions[variable]}}"`
    )
  }

  /**
   * Roots the operator must export outright — they name trees the cluster dir
   * never contains and that nothing on `PATH` can imply.
   *
   * `WIRE_PREFIX_PATH` is deliberately ABSENT: it is RESOLVED rather than
   * demanded (see {@link prefixResolution}), because a host with `nodeop`
   * already installed should not have to name a directory the script can find.
   */
  export const HostSuppliedRoots: readonly StartScriptVariable[] = [
    StartScriptVariable.WIRE_ETH_PATH,
    StartScriptVariable.WIRE_SOLANA_PATH
  ] as const

  /** Human-readable purpose of each host-supplied root, used in its assertion message. */
  export const RootDescriptions: Record<StartScriptVariable, string> = {
    [StartScriptVariable.NODE_DIR]: "daemon directory",
    [StartScriptVariable.CLUSTER_DIR]: "cluster root",
    [StartScriptVariable.WIRE_PREFIX_PATH]: "wire-sysio install prefix",
    [StartScriptVariable.WIRE_ETH_PATH]: "wire-ethereum repository root",
    [StartScriptVariable.WIRE_SOLANA_PATH]: "wire-solana repository root"
  }

  /** The binary whose location on `PATH` implies the install prefix. */
  export const PrefixProbeBinary = "nodeop"

  /**
   * Resolve `$WIRE_PREFIX_PATH`, in precedence order:
   *
   *   1. an explicit `WIRE_PREFIX_PATH` (an operator override always wins);
   *   2. else the parent of a `nodeop` found on `PATH` — an installed host
   *      needs no configuration at all;
   *   3. else `WIRE_BUILD_PATH`, for a tree still pointed at a build dir.
   *
   * Only emitted for daemons whose argv actually references the prefix: anvil,
   * the validator and the debugging server exec their own binaries and must not
   * be made to demand a wire-sysio tree they never touch.
   *
   * @returns Resolution lines, ending in a `:?` guard that fails loudly.
   */
  export function prefixResolution(): string[] {
    const prefix = StartScriptVariable.WIRE_PREFIX_PATH
    return [
      `if [ -z "\${${prefix}:-}" ]; then`,
      `  _wire_nodeop="$(command -v ${PrefixProbeBinary} || true)"`,
      `  if [ -n "$_wire_nodeop" ]; then`,
      `    ${prefix}="$(cd "$(dirname "$_wire_nodeop")/.." && pwd)"`,
      `  elif [ -n "\${WIRE_BUILD_PATH:-}" ]; then`,
      `    ${prefix}="$WIRE_BUILD_PATH"`,
      "  fi",
      "fi",
      `: "\${${prefix}:?set to the ${RootDescriptions[prefix]} (or put ${PrefixProbeBinary} on PATH, or set WIRE_BUILD_PATH)}"`
    ]
  }

  /**
   * The `exec` target for a daemon.
   *
   * A PATH-resolved binary (anvil, solana-test-validator, node) is NOT
   * relocatable — `which()` yields a path like `/home/<user>/.foundry/bin/anvil`
   * that sits under no cluster or repo root, so freezing it ships a script that
   * cannot run anywhere but the build host. Those render as an explicit
   * override falling back to PATH; everything else relocates normally.
   *
   * @param daemon - The daemon being rendered.
   * @param relocations - Ordered relocation table.
   * @returns The shell word to `exec`.
   */
  export function execTarget(
    daemon: DaemonConfig,
    relocations: readonly StartScriptRelocation[]
  ): string {
    return daemon.exeCommandName != null &&
      daemon.exeEnvironmentVariable != null
      ? `"\${${daemon.exeEnvironmentVariable}:-$(command -v ${daemon.exeCommandName})}"`
      : toRelocatableToken(daemon.exe, relocations)
  }

  /**
   * Remove the FIRST contiguous occurrence of `run` from `tokens`.
   *
   * Contiguity is the point: anvil passes the same state-file path to both
   * `--dump-state` and `--load-state`, so removing every occurrence of that
   * path would break `--dump-state`. A `run` that does not appear leaves
   * `tokens` untouched — the build host simply did not produce that flag.
   *
   * @param tokens - The argv to filter.
   * @param run - The contiguous token run to remove.
   * @returns The argv without that run.
   */
  export function removeRun(
    tokens: readonly string[],
    run: readonly string[]
  ): string[] {
    if (run.length === 0) return [...tokens]
    const at = tokens.findIndex((_token, index) =>
      run.every((expected, offset) => tokens[index + offset] === expected)
    )
    return at < 0
      ? [...tokens]
      : [...tokens.slice(0, at), ...tokens.slice(at + run.length)]
  }

  /**
   * The conditional block: an array declaration plus one shell test per
   * condition, appending that condition's (relocated) tokens.
   *
   * Takes the CONDITIONS rather than a whole `DaemonConfig` so the standalone
   * API node's script — which has no daemon and no relocations — renders its
   * `--trace-no-abis` probe through this same function instead of a second copy
   * of the block.
   *
   * @param conditions - The conditions to render (an empty list still emits the
   *   array declaration, which the `exec` line always expands).
   * @param relocations - Ordered relocation table.
   * @returns Lines declaring and populating {@link ConditionalArrayName}.
   */
  export function conditionLines(
    conditions: DaemonConfig["conditions"],
    relocations: readonly StartScriptRelocation[]
  ): string[] {
    return [
      `${ConditionalArrayName}=()`,
      ...conditions.map(condition => {
        const tokens = toRelocatableArgv(condition.tokens, relocations).join(
          " "
        )
        return `${condition.test} && ${ConditionalArrayName}+=(${tokens})`
      }),
      ""
    ]
  }

  /** The `exec` line's trailing expansion of {@link ConditionalArrayName}. */
  export const ConditionalArrayExpansion = `"\${${ConditionalArrayName}[@]}"`
}
