import {
  type BytesType,
  PrivateKey,
  PublicKey,
  Signature
} from "@wireio/sdk-core"
import { ChainKind, OperatorType } from "@wireio/opp-typescript-models"
import type { OperatorAccountWallet } from "./OperatorAccountWallet.js"

/**
 * WIRE-chain (depot-side) signing identity for a bootstrapped operator.
 *
 * Backed by a K1 (secp256k1) keypair generated by `clio create key --k1`
 * during `ClusterManager`'s `generateAndImportKeys` phase and imported
 * into kiod. The string spellings (`PUB_K1_*` / `PVT_K1_*`) are
 * persisted on `NodeState.keys.wireK1` so attach-mode flow tests can
 * reconstruct the same identity without having to re-query kiod.
 *
 * `sign(message)` delegates to sdk-core's `PrivateKey.signMessage` —
 * for K1 that hashes the message with SHA-256 first, then runs ECDSA.
 * For actually pushing WIRE transactions, prefer the harness's
 * `Clio.pushAction` path, which routes through kiod with the operator's
 * `@active` permission; the in-process `privateKey` here is the
 * back-channel for tests that need to compute or verify signatures
 * without going through clio/kiod.
 *
 * There is no chain-native "address" string distinct from the operator's
 * WIRE account name, so `address` is omitted.
 */
export class WireOperatorAccountWallet implements OperatorAccountWallet {
  readonly chain: ChainKind = ChainKind.WIRE

  /**
   * @param name         WIRE account name (e.g. `batchop.a`).
   * @param operatorType Role (BATCH / UNDERWRITER / …).
   * @param publicKey    33-byte K1 compressed pubkey, wrapped as `PUB_K1_*`.
   * @param privateKey   K1 32-byte private key, wrapped as `PVT_K1_*`.
   */
  constructor(
    readonly name: string,
    readonly operatorType: OperatorType,
    readonly publicKey: PublicKey,
    readonly privateKey: PrivateKey
  ) {}

  /** sdk-core uniform signing — SHA-256(message) → K1 ECDSA → `SIG_K1_*`. */
  sign(message: BytesType): Signature {
    return this.privateKey.signMessage(message)
  }
}

export namespace WireOperatorAccountWallet {
  /**
   * Build a WIRE wallet from `PUB_K1_*` / `PVT_K1_*` strings as persisted
   * to `NodeState.keys.wireK1`.
   */
  export function fromStrings(args: {
    name: string
    operatorType: OperatorType
    publicKey: string
    privateKey: string
  }): WireOperatorAccountWallet {
    const { name, operatorType, publicKey, privateKey } = args
    return new WireOperatorAccountWallet(
      name,
      operatorType,
      PublicKey.from(publicKey),
      PrivateKey.from(privateKey)
    )
  }
}
