import { createHash } from "node:crypto"
import * as Fs from "node:fs"
import * as OS from "node:os"
import * as Path from "node:path"

import { EnvelopePersistence } from "@wireio/debugging-server/routes/opp"
import {
  AtomicFile,
  endpointsTypeToKey,
  readEnvelopeRecordsFromDir
} from "@wireio/debugging-shared"
import {
  DebugEnvelopeMetadataRecord,
  DebugOutpostEndpointsType,
  Envelope
} from "@wireio/opp-typescript-models"

/** Endpoint shared by deterministic persistence fixtures. */
export const TestEndpoint = DebugOutpostEndpointsType.OUTPOST_ETHEREUM_DEPOT

/** Canonical data and sidecar paths for one generated envelope. */
export interface EnvelopeFixture {
  readonly data: Uint8Array
  readonly digest: string
  readonly key: string
  readonly dataFile: string
  readonly metadataFile: string
}

/**
 * Create an isolated directory removed by each suite's teardown.
 * @return Absolute temporary storage path.
 */
export function createStorageDir(): string {
  return Fs.mkdtempSync(Path.join(OS.tmpdir(), "envelope-persistence-"))
}

/**
 * Fixture teardown for one isolated temporary storage directory.
 * @param storageDir Temporary storage root to remove.
 */
export function removeStorageDir(storageDir: string): void {
  Fs.rmSync(storageDir, { recursive: true, force: true })
}

/**
 * Serialize a minimal generated envelope with deterministic distinguishing bytes.
 * @param epochIndex Epoch encoded into the envelope and canonical key.
 * @param marker Byte value distinguishing same-epoch payloads.
 * @return Generated protobuf bytes.
 */
export function makeEnvelope(epochIndex: number, marker = 0): Uint8Array {
  return Envelope.toBinary(
    Envelope.create({
      epochIndex,
      epochTimestamp: BigInt(marker),
      envelopeHash: new Uint8Array(32).fill(marker),
      previousEnvelopeHash: new Uint8Array(32),
      messages: []
    })
  )
}

/**
 * Derive the same canonical key and paths as production persistence.
 * @param storageDir Directory containing the final pair.
 * @param epochIndex Epoch encoded into the fixture envelope.
 * @param marker Byte value distinguishing same-epoch payloads.
 * @return Generated bytes, digest, key, and final paths.
 */
export function fixture(
  storageDir: string,
  epochIndex = 42,
  marker = 0
): EnvelopeFixture {
  const data = makeEnvelope(epochIndex, marker),
    digest = createHash("sha256").update(data).digest("hex"),
    endpointKey = endpointsTypeToKey(TestEndpoint)
  if (endpointKey === null) throw new TypeError("test endpoint has no enum key")
  const key = `${String(epochIndex).padStart(8, "0")}-${endpointKey}-${digest.slice(0, 16)}`
  return {
    data,
    digest,
    key,
    dataFile: Path.join(storageDir, `${key}.data`),
    metadataFile: Path.join(storageDir, `${key}.metadata`)
  }
}

/**
 * Build one helper request without bypassing the package-root API.
 * @param storageDir Directory containing the final pair.
 * @param data Exact generated envelope bytes.
 * @param batchOpName Operator name merged into metadata.
 * @return Complete persistence request.
 */
export function request(
  storageDir: string,
  data: Uint8Array,
  batchOpName: string
): EnvelopePersistence.Request {
  return {
    storageDir,
    envelopeData: data,
    batchOpName,
    endpointsType: TestEndpoint
  }
}

/**
 * Construct a Node-style errno for deterministic filesystem faults.
 * @param code Stable Node filesystem error code.
 * @return Error carrying the requested code.
 */
export function errno(code: string): NodeJS.ErrnoException {
  return Object.assign(new Error(code), { code })
}

/**
 * Fail only parent-directory sync after the atomic commit point.
 * @return Partial filesystem override delegating every other operation.
 */
export function directorySyncFault(): Partial<AtomicFile.FileSystem> {
  return {
    open: async (file, flags, mode) => {
      const handle = await Fs.promises.open(file, flags, mode)
      if (flags !== "r") return handle
      return {
        writeFile: data => handle.writeFile(data),
        sync: () => Promise.reject(errno("EIO")),
        close: () => handle.close()
      }
    }
  }
}

/**
 * Decode committed metadata directly from its authoritative bytes.
 * @param storage Canonical metadata path to read.
 * @return Generated metadata record.
 */
export async function metadata(
  storage: EnvelopeFixture
): Promise<DebugEnvelopeMetadataRecord> {
  return DebugEnvelopeMetadataRecord.fromBinary(
    await Fs.promises.readFile(storage.metadataFile)
  )
}

/**
 * Capture only the public atomic diagnostic, rethrowing unexpected failures.
 * @param action Persistence action expected to reject atomically.
 * @return Public atomic publication error.
 */
export async function capturePublishError(
  action: () => Promise<EnvelopePersistence.Result>
): Promise<AtomicFile.PublishError> {
  try {
    await action()
  } catch (error) {
    if (error instanceof AtomicFile.PublishError) return error
    throw error
  }
  throw new TypeError("expected AtomicFile.PublishError")
}

/**
 * Capture only a persistence integrity rejection.
 * @param action Persistence action expected to reject integrity validation.
 * @return Typed persistence integrity error.
 */
export async function captureIntegrityError(
  action: () => Promise<EnvelopePersistence.Result>
): Promise<EnvelopePersistence.IntegrityError> {
  try {
    await action()
  } catch (error) {
    if (error instanceof EnvelopePersistence.IntegrityError) return error
    throw error
  }
  throw new TypeError("expected EnvelopePersistence.IntegrityError")
}

/**
 * Assert direct bytes, generated decoders, checksum geometry, and tolerant reader output.
 * @param storageDir Directory consumed by the production tolerant reader.
 * @param storage Expected data and metadata identity.
 * @param names Expected insertion-ordered metadata names.
 */
export async function expectReadablePair(
  storageDir: string,
  storage: EnvelopeFixture,
  names: readonly string[]
): Promise<void> {
  expect(Buffer.from(await Fs.promises.readFile(storage.dataFile))).toEqual(
    Buffer.from(storage.data)
  )
  const decodedMetadata = await metadata(storage)
  expect(decodedMetadata.checksum).toBe(
    BigInt(`0x${storage.digest.slice(0, 12)}`)
  )
  expect(decodedMetadata.batchOpNames).toEqual(names)
  const records = await readEnvelopeRecordsFromDir(storageDir)
  expect(records).toHaveLength(1)
  expect(records[0]?.epoch).toBe(42)
  expect(records[0]?.envelopes).toHaveLength(1)
  expect(records[0]?.envelopes[0]?.metadata.batchOpNames).toEqual(names)
}

/**
 * Assert the complete sorted final inventory, implicitly excluding atomic temps.
 * @param storageDir Directory whose complete entries are asserted.
 * @param files Expected final entry names.
 */
export function expectFiles(
  storageDir: string,
  files: readonly string[]
): void {
  expect(Fs.readdirSync(storageDir).sort()).toEqual([...files].sort())
}
