// Shared webpack building blocks for the four ql-tool-app bundles (main,
// preload, query-host, renderer). Every bundle lands in dist/app/ (the renderer
// in dist/app/renderer/), transpiled by TypeScript itself through ts-loader in
// transpileOnly mode (type checking is `tsc -b`'s job). swc is NOT used: its
// namespace transform leaves references to companion-namespace members inside
// destructuring patterns (computed keys, default values) unqualified — a
// runtime ReferenceError in exactly the house-style code (companion namespaces +
// destructuring defaults) this package is written in. Every bundle is built
// with a non-eval `source-map` devtool so `script-src 'self'` holds in dev too,
// and `node.__filename: true` so every module's `getLogger(__filename)` gets its
// own `src/...` path (relative to the package) as its logger category.
// webpack.config.mjs is the ONE config the package scripts pass to webpack: it
// exports the four bundles as an array (select some with `--config-name`).
import Fs from "node:fs"
import { createRequire } from "node:module"
import Path from "node:path"

import TypeScript from "typescript"

const requireFromHere = createRequire(import.meta.url)

/**
 * Import a dependency-free TypeScript module (e.g. QLContentSecurityPolicy.ts,
 * AppPaths.ts — Node builtins are the only imports allowed) into the build
 * config by transpiling it with TypeScript — the ONE spelling of a constant
 * stays in src/ while the config consumes it.
 *
 * @param {string} file absolute path
 * @returns {Promise<object>} the module namespace
 */
export async function importTypeScriptModule(file) {
  const { outputText } = TypeScript.transpileModule(Fs.readFileSync(file, "utf8"), {
    compilerOptions: { module: TypeScript.ModuleKind.ESNext, target: TypeScript.ScriptTarget.ES2022 }
  })
  return import(`data:text/javascript;base64,${Buffer.from(outputText).toString("base64")}`)
}

/** The app's build-time identity (etc/app-identity/app-identity.cjs, shared with electron-builder). */
export const Identity = requireFromHere("../app-identity/app-identity.cjs")
/** The package directory; every bundle's `context`, so `node.__filename` stays `src/...`. */
export const PackagePath = Identity.PackagePath
/** The bundle output directory (the packaged app's root). */
export const AppOutputPath = Path.join(PackagePath, "dist", "app")
/** The brand assets (icons generated by scripts/generate-ql-app-icons.mjs). */
export const BrandAssetsPath = Path.join(PackagePath, "resources", "assets", "brand")
/** The runtime path layout and environment variables, from their ONE spelling (src/main/AppPaths.ts). */
export const { AppPaths } = await importTypeScriptModule(Path.join(PackagePath, "src", "main", "AppPaths.ts"))
/** The renderer bundle's directory. */
export const RendererOutputPath = Path.join(AppOutputPath, AppPaths.RendererSubpath)
/** Brand PNGs copied next to main.js (runtime window / about-panel icon — AppPaths.IconFilename — and a smaller size). */
export const RuntimeIconFilenames = ["icon-256.png", AppPaths.IconFilename]
/** webpack modes. */
export const Mode = { development: "development", production: "production" }
/** The webpack target of the bundles without Node (preload, renderer). */
export const WebTarget = "web"
/**
 * `resolve.fallback` of every {@link WebTarget} bundle. No Node polyfills: an
 * accidental Node-builtin import FAILS the build; the one `false` entry exists
 * because sdk-core's BLS code reaches Node `crypto` only when
 * `globalThis.crypto` is absent (it never is in Chromium).
 */
export const WebFallback = { crypto: false }
/**
 * Dual (CJS + ESM) packages pinned to ONE build in every bundle. The workspace's
 * CJS packages (`@wireio/ql-shared` lib/cjs, …) `require` them while app sources
 * `import` them; without the pin webpack would bundle both builds — two
 * `@wireio/shared` LoggingManagers (the CJS one never sees the installed file
 * appender, so ql-shared's records are lost) and two copies of everything else.
 */
export const SingleInstancePackages = [
  "@wireio/shared",
  "@wireio/shared/node",
  "@wireio/sdk-core",
  "@wireio/cluster-tool-shared",
  "zod"
]

/** `resolve.alias` pinning {@link SingleInstancePackages} to their CJS entries. */
export function createSingleInstanceAliases() {
  const requireFromPackage = createRequire(Path.join(PackagePath, "package.json"))
  return Object.fromEntries(SingleInstancePackages.map(name => [`${name}$`, requireFromPackage.resolve(name)]))
}

/** ts-loader options: TypeScript's own emit (ESM modules for webpack, external source maps). */
export function createTypeScriptLoaderOptions() {
  return {
    transpileOnly: true,
    configFile: Path.join(PackagePath, "tsconfig.renderer.json"),
    compilerOptions: {
      module: "esnext",
      moduleResolution: "bundler",
      target: "es2022",
      sourceMap: true,
      inlineSourceMap: false,
      inlineSources: false,
      declaration: false,
      declarationMap: false,
      composite: false,
      incremental: false
    }
  }
}

/**
 * The webpack mode of a build (`--mode`; production when not given) — resolved
 * here only, for every bundle.
 *
 * @param {{ mode?: string }} argv webpack-cli arguments
 * @returns {string} development | production
 */
export function modeOf(argv = {}) {
  return argv.mode ?? Mode.production
}

/**
 * The common config of one bundle.
 *
 * @param {object} options
 * @param {string} options.name compiler name (`--config-name`)
 * @param {string} options.target webpack target ({@link WebTarget} bundles get {@link WebFallback})
 * @param {Record<string, string>} options.entry entry map
 * @param {string} options.outputPath output directory
 * @param {boolean | string} [options.dirname] `node.__dirname` (false = the real directory)
 * @param {import("webpack").Configuration["output"]} [options.output] members added to / overriding the common output
 * @param {{ mode?: string }} [argv] webpack-cli arguments (the mode)
 * @returns {import("webpack").Configuration}
 */
export function createCommonConfig({ name, target, entry, outputPath, dirname = false, output = {} }, argv = {}) {
  return {
    name,
    target,
    mode: modeOf(argv),
    context: PackagePath,
    entry,
    devtool: "source-map",
    output: {
      path: outputPath,
      filename: "[name].js",
      devtoolModuleFilenameTemplate: "webpack://ql-tool-app/[resource-path]",
      ...output
    },
    node: { __filename: true, __dirname: dirname },
    resolve: {
      alias: createSingleInstanceAliases(),
      extensions: [".ts", ".tsx", ".js", ".mjs", ".cjs", ".json"],
      extensionAlias: { ".js": [".ts", ".tsx", ".js"] },
      ...(target === WebTarget && { fallback: WebFallback })
    },
    module: {
      rules: [
        {
          test: /\.tsx?$/,
          exclude: /node_modules/,
          use: { loader: "ts-loader", options: createTypeScriptLoaderOptions() }
        }
      ]
    },
    performance: { hints: false },
    stats: "errors-warnings"
  }
}

/** Emits the runtime brand icons into the main bundle's directory (AppPaths.AssetsSubpath). */
export class RuntimeIconsPlugin {
  apply(compiler) {
    const { RawSource } = compiler.webpack.sources
    compiler.hooks.thisCompilation.tap("RuntimeIconsPlugin", compilation => {
      compilation.hooks.processAssets.tap(
        { name: "RuntimeIconsPlugin", stage: compiler.webpack.Compilation.PROCESS_ASSETS_STAGE_ADDITIONAL },
        () =>
          RuntimeIconFilenames.forEach(filename => {
            const file = Path.join(BrandAssetsPath, filename)
            compilation.fileDependencies.add(file)
            compilation.emitAsset(Path.join(AppPaths.AssetsSubpath, filename), new RawSource(Fs.readFileSync(file)))
          })
      )
    })
  }
}

/** Writes dist/app/package.json — the packaged app's own manifest (no dependencies: everything is bundled). */
export class AppManifestPlugin {
  apply(compiler) {
    const { RawSource } = compiler.webpack.sources
    compiler.hooks.thisCompilation.tap("AppManifestPlugin", compilation => {
      compilation.hooks.processAssets.tap(
        { name: "AppManifestPlugin", stage: compiler.webpack.Compilation.PROCESS_ASSETS_STAGE_ADDITIONAL },
        () => {
          const app = {
            name: Identity.ManifestName,
            productName: Identity.ProductName,
            version: Identity.Version,
            description: Identity.Description,
            author: { name: Identity.Author },
            homepage: Identity.Homepage,
            desktopName: Identity.DesktopName,
            main: AppPaths.MainFilename,
            private: true
          }
          compilation.emitAsset("package.json", new RawSource(`${JSON.stringify(app, null, 2)}\n`))
        }
      )
    })
  }
}
